#!/usr/bin/env python

import Timer 
import os
import sys 

tt = Timer.timer() 

def runcmd(cmd):
	''' run command cmd and exit if errors ''' 
	x = os.system(cmd)
	if (x != 0):
		sys.exit()

runcmd('foamListTimes -rm') # delete previous time steps 
if (os.path.isfile('0/yPlus')): # remove previous yPlus 
	runcmd('rm 0/yPlus')
runcmd('blockMesh') # generate mesh 
runcmd('decomposePar -force') # decompose for parallel run 
# run pipe into log 
runcmd('mpirun -np 4 interFoam -parallel | tee log')
runcmd('reconstructPar') # reconstruct parallel folders 
runcmd('interFoam -postProcess -func yPlus') # generate yPlus 

time, str = tt.stop()

# make notification if wall time is longer than a minute 
if (time > 60):
	os.system('notify-send --urgency=low -i " " "openfoam done" \
		"run completed in %s"' % (str))